### ISSUE TITLE
Failure in test suite with upcoming igraph version

### ISSUE THREAD

**Issue by szhorvat** [cadam00/priorCON#1]
I am writing on behalf of igraph. The `priorCON` test suite fails with the upcoming igraph version, as it assumes a specific output for `igraph::cluster_louvain()`. The issue is here:

https://github.com/cadam00/priorCON/blob/8c9f27d80140d949df5fbd0e60384a1df3f473ec/tests/testthat/test-get_metrics.r#L34-L40

You can see a discussion of the test output here: https://github.com/igraph/rigraph/pull/1470#issuecomment-2331022737

`igraph::cluster_louvain()` implements a stochastic algorithm. With such algorithms, we do not guarantee that the output won't change for the same random seed across bugfix versions. It will in fact change in the next R/igraph release—this was necessitated by a bugfix (https://github.com/igraph/igraph/issues/2650).

What we do guarantee is unchanged statistical properties.

Let me know if you have questions 😊

**Comment by cadam00** [comment]
Thanks a lot!!!! I just took care of it and I do not use the exact values of the memberships for testing!!! Is it alright now?
I corrected the Github version, but I think that I must wait about 2 weeks before resubmitting on CRAN (first package publish was done on 2024-08-19).

Do you think that I might resubmit it even right now on CRAN?

**Comment by szhorvat** [comment]
Thanks so much for the amazingly quick response!

@krlmlr @maelle, do you have any input for the question above? Or generally about the urgency of resubmitting?

(I don't do that much R myself, I was just the one responsible for the bugfix that triggered the issue here :-)

**Comment by krlmlr** [comment]
Thanks. An update now should be fine, it would only be flagged if it's less than a week ago (or if you had more than six updates in the last 180 days).

**Comment by cadam00** [comment]
Ok thanks!!! I will make a try!!!! I close this issue now and in case that something else prompts please do not hesitate to notify me!!!!
